### ISSUE TITLE
RROR: Command error: Unrecognized field "projectCode" (class org.icgc.dcc.storage.client.metadata.Entity), not marked as ignorable (4 known properties: "id", "createdTime", "gnosId", "fileName"])

### ISSUE THREAD

**Issue by linwang6** [icgc-dcc/dcc-download#43]
Hi all,
I am using icgc-storage-client to download data from ICGC, I have access token from ICGC DACO. There is error when I run the icgc-storage-client,

./icgc-storage-client --quiet download --object-id ddcdd044-adda-5f09-8849-27d6038f8ccd --output-dir /tmp/output_files/
Starting...
                                                                                

Running...
                                                                                

Downloading...
                                                                                
ERROR: Command error: Unrecognized field "projectCode" (class org.icgc.dcc.storage.client.metadata.Entity), not marked as ignorable (4 known properties: "id", "createdTime", "gnosId", "fileName"])
 at [Source: https://meta.icgc.org/entities/ddcdd044-adda-5f09-8849-27d6038f8ccd; line: 1, column: 159] (through reference chain: org.icgc.dcc.storage.client.metadata.Entity["projectCode"])
Please check the log for detailed error messages

I will be appreciated if you can give some advices. Thanks.

**Comment by andricDu** [comment]
wrong repo.
